package br.edu.ifpb.firecorp.domain.model;

public enum TipoPatente {
	
	SOLDADO, CABO, TERCEIRO_SARGENTO, SEGUNDO_SARGENTO, PRIMEIRO_SARGENTO, SUBTENENTE, SEGUNDO_TENENTE, PRIMEIRO_TENENTE, CAPITAO, MAJOR, TENENTE_CORONEL, CORONEL

}
